/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package version_2_1;

import javax.swing.JFileChooser;

/**
 *
 * @author christos
 */
public class JFileChooser_SelectMoviesFolder extends JFileChooser {

    /**
     * Creates new form JFileChooser_SelectMoviesFolder
     */
    public JFileChooser_SelectMoviesFolder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setAcceptAllFileFilterUsed(false);
        setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
