/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package version_2_1;

import _MainPackage.Main;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author christos
 */
public class jPanel_SelectMoviesFolder extends javax.swing.JPanel {

    /**
     * Creates new form jPanel_SelectMoviesFolder
     */
    public jPanel_SelectMoviesFolder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jFileChooserPn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Path = new javax.swing.JTextField();
        jButton_Browse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton_Exit = new javax.swing.JButton();
        jButton_Ok = new javax.swing.JButton();
        jLoadingPn = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new java.awt.CardLayout());

        jFileChooserPn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 0));
        jFileChooserPn.setLayout(new java.awt.GridLayout(3, 0));

        jLabel9.setText("  Insert movies folder path");
        jFileChooserPn.add(jLabel9);

        jTextField_Path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PathActionPerformed(evt);
            }
        });

        jButton_Browse.setText("Browse");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jTextField_Path, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton_Browse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jTextField_Path, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jButton_Browse))
        );

        jFileChooserPn.add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 1, 1));

        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_Ok.setText("Ok");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .add(jButton_Exit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton_Ok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jButton_Exit)
                .add(jButton_Ok))
        );

        jFileChooserPn.add(jPanel1);

        add(jFileChooserPn, "card1");

        jLoadingPn.setLayout(new java.awt.GridLayout(4, 0));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 75, Short.MAX_VALUE)
        );

        jLoadingPn.add(jPanel3);

        jLabel10.setText("Loading...");
        jLoadingPn.add(jLabel10);

        jProgressBar1.setIndeterminate(true);
        jLoadingPn.add(jProgressBar1);

        add(jLoadingPn, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_PathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PathActionPerformed

    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        // TODO add your handling code here:
        //        int returnVal =
        jFileChooser.showOpenDialog(this);
        File file = jFileChooser.getSelectedFile();
        //        System.out.println(file.getAbsolutePath());

        jTextField_Path.setText(file.getAbsolutePath());
        
        
        Properties prop = new Properties();
        try {
            prop.load(new FileInputStream(Main.propertiesFile));
            prop.setProperty("MoviesDirectory", file.getAbsolutePath());
            
        } catch (IOException ex) {
            Logger.getLogger(jPanel_SelectMoviesFolder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
        /* Check if the user give a correct path
        */
        if (jTextField_Path.getText().equals("")) {
            // Invalid path
            JOptionPane.showMessageDialog(this, "Please choose a valid file path.", "Path error", JOptionPane.ERROR_MESSAGE);
            // Clean path text field
            jTextField_Path.setText("");
        } else {
            File moviesFile = new File(jTextField_Path.getText());
            
            if (moviesFile.exists()) {
                // Use thread to change card to avoid lagging
                //                Thread thr1 = new Thread(r1);
                //                thr1.start();

                Properties prop = new Properties();
                try {
                    prop.load(new FileInputStream(Main.propertiesFile));
                    prop.setProperty("MoviesDirectory", moviesFile.getAbsolutePath());
                } catch (IOException ex) {
                    Logger.getLogger(jPanel_SelectMoviesFolder.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                // Get data!
                try {
                    Main.createTittleYearLists();
                    Main.getMoviesImages();
                } catch (MalformedURLException ex) {
                    Logger.getLogger(jPanel_SelectMoviesFolder.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(jPanel_SelectMoviesFolder.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                // Invalid path
                JOptionPane.showMessageDialog(this, "Please choose a valid file path.", "Path error", JOptionPane.ERROR_MESSAGE);
                // Clean path text field
                jTextField_Path.setText("");
            }

        }
    }//GEN-LAST:event_jButton_OkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JPanel jFileChooserPn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLoadingPn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField_Path;
    // End of variables declaration//GEN-END:variables
}
