/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package version_2_1;

import support.tools.Exist;
import support.tools.ImageProcess;
import java.awt.Image;
import java.util.Properties;
import javax.swing.ImageIcon;
import org.w3c.dom.NodeList;

/**
 *
 * @author christos
 */
public class jPanel_MoviesImage extends javax.swing.JPanel {

    int movieCounter;
    String MoviesDataXML = MyMovies_v2_1.MoviesDataXML;
    String MoviesListTXT = MyMovies_v2_1.MoviesListTXT;
    String ServerResponseTXT = MyMovies_v2_1.ServerResponseTXT;
    String MoviesPosterDIR = MyMovies_v2_1.MoviesPosterDIR;
    /**
     * Creates new form jPanel_MoviesImage
     */
    public jPanel_MoviesImage(int movieID) {

        initComponents();

        movieCounter = movieID;
        
        movieDataDisplay();

    }

    private void movieDataDisplay() {
        String movieXpath = "//movie[" + movieCounter + "]/title";
        NodeList movieTitle = Exist.executeGetQuery(movieXpath, MoviesDataXML);

        String yearXpath = "//movie[" + movieCounter + "]/year";
        NodeList movieYear = Exist.executeGetQuery(yearXpath, MoviesDataXML);

        String runtimeXpath = "//movie[" + movieCounter + "]/runtime";
        NodeList movieRuntime = Exist.executeGetQuery(runtimeXpath, MoviesDataXML);

        String ratingXpath = "//movie[" + movieCounter + "]/rating";
        NodeList movieRating = Exist.executeGetQuery(ratingXpath, MoviesDataXML);

        if (movieTitle.getLength() > 0) {
            String title = movieTitle.item(0).getTextContent().trim();
            String year = movieYear.item(0).getTextContent().trim();
            String runtime = movieRuntime.item(0).getTextContent().trim();
            String rating = movieRating.item(0).getTextContent().trim();



            jLabel_Runtime_value.setText(runtime);
            jLabel_Rating_value.setText(rating + " / 10");

            String imgFile = MoviesPosterDIR + title + year + ".jpg";

            Image origPoster = new ImageIcon(imgFile).getImage();
            int width = 300;
            int height = 400;
            Image resizedPoster = new ImageIcon(ImageProcess.getScaledImage(origPoster, width, height )).getImage();
            ImageIcon post = new ImageIcon(resizedPoster);
            jLabel_PosterImg_value.setIcon(post);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Center = new javax.swing.JPanel();
        jLabel_PosterImg_value = new javax.swing.JLabel();
        jPanel_South = new javax.swing.JPanel();
        jLabel_Runtime_value = new javax.swing.JLabel();
        jLabel_Runtime = new javax.swing.JLabel();
        jLabel_Rating = new javax.swing.JLabel();
        jLabel_Rating_value = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 485));
        setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout jPanel_CenterLayout = new org.jdesktop.layout.GroupLayout(jPanel_Center);
        jPanel_Center.setLayout(jPanel_CenterLayout);
        jPanel_CenterLayout.setHorizontalGroup(
            jPanel_CenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_CenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel_PosterImg_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_CenterLayout.setVerticalGroup(
            jPanel_CenterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_CenterLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel_PosterImg_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel_Center, java.awt.BorderLayout.CENTER);

        jLabel_Runtime_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLabel_Runtime.setText("Runtime");

        jLabel_Rating.setText("Rating");

        jLabel_Rating_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel_SouthLayout = new org.jdesktop.layout.GroupLayout(jPanel_South);
        jPanel_South.setLayout(jPanel_SouthLayout);
        jPanel_SouthLayout.setHorizontalGroup(
            jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_SouthLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .add(jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel_Rating)
                    .add(jLabel_Runtime))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel_Runtime_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel_Rating_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_SouthLayout.setVerticalGroup(
            jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_SouthLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel_Runtime)
                    .add(jLabel_Runtime_value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel_SouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel_Rating_value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel_Rating))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel_South, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_PosterImg_value;
    private javax.swing.JLabel jLabel_Rating;
    private javax.swing.JLabel jLabel_Rating_value;
    private javax.swing.JLabel jLabel_Runtime;
    private javax.swing.JLabel jLabel_Runtime_value;
    private javax.swing.JPanel jPanel_Center;
    private javax.swing.JPanel jPanel_South;
    // End of variables declaration//GEN-END:variables
}
