/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package version_2_1;

import support.tools.Exist;
import org.w3c.dom.NodeList;

/**
 *
 * @author christos
 */
public class jPanel_MoviesInfo extends javax.swing.JPanel {
    
    int movieCounter;
    String MoviesDataXML = MyMovies_v2_1.MoviesDataXML;
    String MoviesListTXT = MyMovies_v2_1.MoviesListTXT;
    String ServerResponseTXT = MyMovies_v2_1.ServerResponseTXT;
    
    /**
     * Creates new form jPanel_MoviesInfo
     */
    public jPanel_MoviesInfo(int movieID) {
        
        initComponents();
        
        movieCounter = movieID;
        
        movieDataDisplay();
        
    }
    
    
    
    private void movieDataDisplay() {
        String movieXpath = "//movie[" + movieCounter + "]/title";
        NodeList movieTitle = Exist.executeGetQuery(movieXpath, MoviesDataXML);

        String yearXpath = "//movie[" + movieCounter + "]/year";
        NodeList movieYear = Exist.executeGetQuery(yearXpath, MoviesDataXML);

        String genreXpath = "//movie[" + movieCounter + "]/genre";
        NodeList movieGenre = Exist.executeGetQuery(genreXpath, MoviesDataXML);

        String plotXpath = "//movie[" + movieCounter + "]/plot";
        NodeList moviePlot = Exist.executeGetQuery(plotXpath, MoviesDataXML);

        String writerXpath = "//movie[" + movieCounter + "]/writer";
        NodeList movieWriter = Exist.executeGetQuery(writerXpath, MoviesDataXML);

        String actorXpath = "//movie[" + movieCounter + "]/actors";
        NodeList movieActor = Exist.executeGetQuery(actorXpath, MoviesDataXML);

        if (movieTitle.getLength() > 0) {

            String title = movieTitle.item(0).getTextContent().trim();
            String year = movieYear.item(0).getTextContent().trim();
            String genre = movieGenre.item(0).getTextContent().trim();
            String plot = moviePlot.item(0).getTextContent().trim();
            String writer = movieWriter.item(0).getTextContent().trim();
            String[] actorTab = movieActor.item(0).getTextContent().trim().split(", ");
            String actor = "";
            for (int i = 0; i < actorTab.length; i++) {
                actor = actor + actorTab[i] + "\n";
            }

            jLabel_Title_value.setText(title);
            jLabel_Year_value.setText(year);
            jLabel_Genre_value.setText(genre);
            jLabel_Writer_value.setText(writer);
            jTextPane_Actors_value.setText(actor);
            jTextPane_Plot_value.setText(plot);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Title = new javax.swing.JLabel();
        jLabel_Year = new javax.swing.JLabel();
        jLabel_Genre = new javax.swing.JLabel();
        jLabel_Writer = new javax.swing.JLabel();
        jLabel_Actors = new javax.swing.JLabel();
        jLabel_Plot = new javax.swing.JLabel();
        jLabel_Title_value = new javax.swing.JLabel();
        jLabel_Year_value = new javax.swing.JLabel();
        jLabel_Genre_value = new javax.swing.JLabel();
        jLabel_Writer_value = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_Actors_value = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane_Plot_value = new javax.swing.JTextPane();

        jLabel_Title.setText("Title");

        jLabel_Year.setText("Year");

        jLabel_Genre.setText("Genre");

        jLabel_Writer.setText("Writer");

        jLabel_Actors.setText("Actors");

        jLabel_Plot.setText("Plot");

        jLabel_Title_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLabel_Year_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLabel_Genre_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLabel_Writer_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jTextPane_Actors_value.setEditable(false);
        jTextPane_Actors_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jScrollPane3.setViewportView(jTextPane_Actors_value);

        jTextPane_Plot_value.setEditable(false);
        jTextPane_Plot_value.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jScrollPane4.setViewportView(jTextPane_Plot_value);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel_Title)
                    .add(jLabel_Year)
                    .add(jLabel_Genre)
                    .add(jLabel_Writer)
                    .add(jLabel_Actors)
                    .add(jLabel_Plot))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel_Title_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel_Year_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel_Genre_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel_Writer_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .add(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel_Title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel_Title_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel_Year)
                    .add(jLabel_Year_value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel_Genre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel_Genre_value, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel_Writer)
                    .add(jLabel_Writer_value, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel_Actors)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel_Plot)
                        .add(0, 144, Short.MAX_VALUE))
                    .add(jScrollPane4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Actors;
    private javax.swing.JLabel jLabel_Genre;
    private javax.swing.JLabel jLabel_Genre_value;
    private javax.swing.JLabel jLabel_Plot;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Title_value;
    private javax.swing.JLabel jLabel_Writer;
    private javax.swing.JLabel jLabel_Writer_value;
    private javax.swing.JLabel jLabel_Year;
    private javax.swing.JLabel jLabel_Year_value;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane_Actors_value;
    private javax.swing.JTextPane jTextPane_Plot_value;
    // End of variables declaration//GEN-END:variables
}
